export const icon_svgs = {
  sound: "sound.svg",
  dictionary: "",
  summarize: "",
  highlight: "",
  font: "",
  save: "",
  download: "",
  home: "",
  library: "",
  profile: "",
  close: "",
  folder: "",
  addFolder: "",
  link: "",
  arrowRight: "",
  plus: "",
  search: "",
  check: "",
};
