export const icon_svgs = {
    sound: "sound.svg",
    dictionary: "dictionary.svg",
    summarize: "summarize.svg",
    highlight: "highlight.svg",
    font: "font.svg",
    save: "save.svg",
    download: "download.svg",
    home: "home.svg",
    library: "library.svg",
    profile: "profile.svg",
    close: "close.svg",
    folder: "folder.svg",
    addFolder: "addFolder.svg",
    link: "link.svg",
    arrowRight: "arrowRight.svg",
    plus: "plus.svg",
    search: "search.svg",
    check: "check.svg",
    upload: "upload.svg"
};
